name: Deploy static website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: "20"

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
          retention-days: 30

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' # Ne déployer que sur push, pas sur PR

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_PATH_PROD }}
          # Options avancées
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.log
          # Supprimer les fichiers sur le serveur qui n'existent plus localement
          dangerous-clean-slate: false
          # Afficher les détails du déploiement
          log-level: verbose
          # Port FTP (21 par défaut pour FTP, 22 pour SFTP)
          port: 21
          # Utiliser SFTP au lieu de FTP (plus sécurisé)
          protocol: ftp
          # Timeout en secondes
          timeout: 600000
